# -*- coding: utf-8 -*-
"""Another copy of Amazon_EDA_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ctMxwVhAR6-vt4GmkqykT6Yir9CVZQnP

# **Amazon Sale Report EDA Project**

# **Aim of the Project**

The aim of this project is to perform Exploratory Data Analysis (EDA) on Amazon sale report data to:

 * Understand the overall structure, patterns, and trends in the sales.

 * Identify and clean missing or duplicate data.

 * Detect outliers and analyze their effect on sales insights.

 * Visualize sales performance by category, location, fulfillment method, and over time.

 * Reveal relationships between variables using correlation analysis.

# ***Importing the modules***
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""# ***Loading the data***"""

df = pd.read_csv("Amazon Sale Report.csv")
df

"""# ***Shape of the dataset***"""

df.shape

"""# Extracting of the data"""

df.head()

df.tail()

"""# ***Info Of The DataSet***"""

df.info()

"""# ***DESCRIPTIVE STATISTICS***

***Descriptive Statistics (Numerical)***
"""

df.describe()

"""***Descriptive Statistics (Categorical)***"""

df.describe(include='object')

"""
#***Droping unnecessary columns***
"""

df = df.drop(columns=['Unnamed: 22', 'index'], errors='ignore')

df.columns

"""# ***Duplicates check and Removal***"""

df[["SKU"]]

"""**What is SKU?**

*A SKU, or Stock Keeping Unit, is a unique alphanumeric code that businesses use to identify and track their products internally*

***Purpose:***

*SKUs are used to differentiate between products, especially when variations like color, size, or style exist. For example, a t-shirt might have one SKU for a small, blue version and another for a large, red version.*

 **Source** - ***GOOGLE***
"""

df.drop_duplicates(['Order ID', 'SKU', 'Date'],keep = 'first', inplace = True)

print("After dropping duplicates shape of the dataset is\n")
df.shape

"""# ***Null values counts***"""

df.isnull()

df.isnull().sum()

"""# ***No of Unique values in each Column***"""

print("\n--- Unique Values Per Column ---")
print(df.nunique())

df.dropna(inplace=True)

df.isnull().sum()

df.shape

"""# ***OUTLIER DETECTION (Boxplot for Amount)***"""

plt.figure()
sns.boxplot(x=df['Amount'])
plt.title("Outlier Detection in 'Amount'")
plt.tight_layout()
plt.show()

"""***Create a filtered copy for outlier-removed analysis (IQR method)***"""

Q1 = df['Amount'].quantile(0.25)
Q3 = df['Amount'].quantile(0.75)
IQR = Q3 - Q1
filtered_df = df[(df['Amount'] >= Q1 - 1.5 * IQR) & (df['Amount'] <= Q3 + 1.5 * IQR)]

"""#***boxplot after removing outliers***"""

plt.figure()
sns.boxplot(x=filtered_df['Amount'])
plt.title("'Amount' After Removing Outliers")
plt.tight_layout()
plt.show()

"""#***Correlation Heatmap***"""

plt.figure(figsize=(10, 6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm', linewidths=0.5, fmt=".2f")
plt.title("Correlation Heatmap of Numerical Features")
plt.tight_layout()
plt.show()

"""# ***Top Product Categories***"""

top_categories = df['Category'].value_counts().head(10)
plt.figure()
sns.barplot(x=top_categories.index, y=top_categories.values, palette="Set1")
plt.title("Top 10 Product Categories")
plt.xticks(rotation=45)
plt.ylabel("Number of Orders")
plt.xlabel("Category")
plt.tight_layout()
plt.show()

"""# ***SALES TREND OVER TIME***"""

df_grouped_by_date = df.groupby('Date')['Amount'].sum()
plt.figure(figsize=(12,5))
df_grouped_by_date.plot(color='blue')
plt.title('Sales Trend Over Time')
plt.xlabel('Date')
plt.ylabel('Total Sales')
plt.tight_layout()
plt.show()

"""# ***Top Shipping Cities***"""

top_cities = df['ship-city'].value_counts().head(10)
plt.figure()
sns.barplot(x=top_cities.values, y=top_cities.index, color="red",edgecolor="black")
plt.title("Top 10 Shipping Cities")
plt.xlabel("Number of Orders")
plt.ylabel("City")
plt.tight_layout()
plt.show()

"""# ***Fulfillment Distribution***"""

fulfilment_counts = df['Fulfilment'].value_counts()
plt.figure()
sns.barplot(x=fulfilment_counts.index, y=fulfilment_counts.values, color="orange",edgecolor="black")
plt.title("Fulfilment Method Distribution")
plt.ylabel("Number of Orders")
plt.xlabel("Fulfilled By")
plt.tight_layout()
plt.show()

"""# **Conclusions**
 * Cleaned and preprocessed the dataset by removing duplicates, null values, and outliers.

 * Majority of sales came from categories like Set and Kurta.
**bold text**
 * Top ordering cities were Bengaluru, Hyderabad, and Mumbai.

 * Most orders were fulfilled by Amazon, indicating strong reliance on its logistics.

 * Sales peaked during April–May, showing possible seasonal trends.

 * Correlation analysis showed meaningful relationships between some numerical fields.


"""

